version: "3"
services:
    mongodb:
        image: mongo
        expose:
            - "27017"
        volumes:
            - /home/daxnet/mongodb/data:/data/db:Z
        container_name: mongodb

    reposample:
        build:
            context: .
            dockerfile: Dockerfile
        image:
            reposample
        ports:
            - "9023:9023"
        links:
            - mongodb
        environment:
            - mongo:host=mongodb
